// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: protos/wordle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	Submit(ctx context.Context, in *WordGuess, opts ...grpc.CallOption) (*WordGuessResponse, error)
	Start(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*StartResponse, error)
	GetGameStatus(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*GameStatus, error)
	GetMyRank(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Rank, error)
	GetTodayRanks(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*DayRanks, error)
	GetRanksHistory(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*RanksHistory, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Submit(ctx context.Context, in *WordGuess, opts ...grpc.CallOption) (*WordGuessResponse, error) {
	out := new(WordGuessResponse)
	err := c.cc.Invoke(ctx, "/main.GameService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Start(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/main.GameService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameStatus(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*GameStatus, error) {
	out := new(GameStatus)
	err := c.cc.Invoke(ctx, "/main.GameService/GetGameStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetMyRank(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Rank, error) {
	out := new(Rank)
	err := c.cc.Invoke(ctx, "/main.GameService/GetMyRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetTodayRanks(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*DayRanks, error) {
	out := new(DayRanks)
	err := c.cc.Invoke(ctx, "/main.GameService/GetTodayRanks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetRanksHistory(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*RanksHistory, error) {
	out := new(RanksHistory)
	err := c.cc.Invoke(ctx, "/main.GameService/GetRanksHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	Submit(context.Context, *WordGuess) (*WordGuessResponse, error)
	Start(context.Context, *UserName) (*StartResponse, error)
	GetGameStatus(context.Context, *UserName) (*GameStatus, error)
	GetMyRank(context.Context, *UserName) (*Rank, error)
	GetTodayRanks(context.Context, *EmptyMessage) (*DayRanks, error)
	GetRanksHistory(context.Context, *EmptyMessage) (*RanksHistory, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) Submit(context.Context, *WordGuess) (*WordGuessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedGameServiceServer) Start(context.Context, *UserName) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedGameServiceServer) GetGameStatus(context.Context, *UserName) (*GameStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameStatus not implemented")
}
func (UnimplementedGameServiceServer) GetMyRank(context.Context, *UserName) (*Rank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyRank not implemented")
}
func (UnimplementedGameServiceServer) GetTodayRanks(context.Context, *EmptyMessage) (*DayRanks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodayRanks not implemented")
}
func (UnimplementedGameServiceServer) GetRanksHistory(context.Context, *EmptyMessage) (*RanksHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRanksHistory not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordGuess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Submit(ctx, req.(*WordGuess))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Start(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/GetGameStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameStatus(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetMyRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetMyRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/GetMyRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetMyRank(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetTodayRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetTodayRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/GetTodayRanks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetTodayRanks(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetRanksHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetRanksHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GameService/GetRanksHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetRanksHistory(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _GameService_Submit_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _GameService_Start_Handler,
		},
		{
			MethodName: "GetGameStatus",
			Handler:    _GameService_GetGameStatus_Handler,
		},
		{
			MethodName: "GetMyRank",
			Handler:    _GameService_GetMyRank_Handler,
		},
		{
			MethodName: "GetTodayRanks",
			Handler:    _GameService_GetTodayRanks_Handler,
		},
		{
			MethodName: "GetRanksHistory",
			Handler:    _GameService_GetRanksHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/wordle.proto",
}
