// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: protos/wordle.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterStatus int32

const (
	CharacterStatus_NOT_PRESENT           CharacterStatus = 0
	CharacterStatus_PRESENT_BUT_MISPLACED CharacterStatus = 1
	CharacterStatus_CORRECT               CharacterStatus = 2
)

// Enum value maps for CharacterStatus.
var (
	CharacterStatus_name = map[int32]string{
		0: "NOT_PRESENT",
		1: "PRESENT_BUT_MISPLACED",
		2: "CORRECT",
	}
	CharacterStatus_value = map[string]int32{
		"NOT_PRESENT":           0,
		"PRESENT_BUT_MISPLACED": 1,
		"CORRECT":               2,
	}
)

func (x CharacterStatus) Enum() *CharacterStatus {
	p := new(CharacterStatus)
	*p = x
	return p
}

func (x CharacterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_wordle_proto_enumTypes[0].Descriptor()
}

func (CharacterStatus) Type() protoreflect.EnumType {
	return &file_protos_wordle_proto_enumTypes[0]
}

func (x CharacterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterStatus.Descriptor instead.
func (CharacterStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_NOT_ATTEMPTED Status = 0
	Status_PENDING       Status = 1
	Status_WON           Status = 2
	Status_LOST          Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NOT_ATTEMPTED",
		1: "PENDING",
		2: "WON",
		3: "LOST",
	}
	Status_value = map[string]int32{
		"NOT_ATTEMPTED": 0,
		"PENDING":       1,
		"WON":           2,
		"LOST":          3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_wordle_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_wordle_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{1}
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{0}
}

type WordGuess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Word     string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *WordGuess) Reset() {
	*x = WordGuess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordGuess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordGuess) ProtoMessage() {}

func (x *WordGuess) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordGuess.ProtoReflect.Descriptor instead.
func (*WordGuess) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{1}
}

func (x *WordGuess) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WordGuess) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordGuessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus Status      `protobuf:"varint,1,opt,name=gameStatus,proto3,enum=main.Status" json:"gameStatus,omitempty"`
	WordMatch  *WordStatus `protobuf:"bytes,2,opt,name=wordMatch,proto3" json:"wordMatch,omitempty"`
}

func (x *WordGuessResponse) Reset() {
	*x = WordGuessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordGuessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordGuessResponse) ProtoMessage() {}

func (x *WordGuessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordGuessResponse.ProtoReflect.Descriptor instead.
func (*WordGuessResponse) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{2}
}

func (x *WordGuessResponse) GetGameStatus() Status {
	if x != nil {
		return x.GameStatus
	}
	return Status_NOT_ATTEMPTED
}

func (x *WordGuessResponse) GetWordMatch() *WordStatus {
	if x != nil {
		return x.WordMatch
	}
	return nil
}

type UserName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *UserName) Reset() {
	*x = UserName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserName) ProtoMessage() {}

func (x *UserName) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserName.ProtoReflect.Descriptor instead.
func (*UserName) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{3}
}

func (x *UserName) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartResponse string `protobuf:"bytes,1,opt,name=startResponse,proto3" json:"startResponse,omitempty"`
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{4}
}

func (x *StartResponse) GetStartResponse() string {
	if x != nil {
		return x.StartResponse
	}
	return ""
}

type GameStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus Status `protobuf:"varint,1,opt,name=gameStatus,proto3,enum=main.Status" json:"gameStatus,omitempty"`
}

func (x *GameStatus) Reset() {
	*x = GameStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatus) ProtoMessage() {}

func (x *GameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatus.ProtoReflect.Descriptor instead.
func (*GameStatus) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{5}
}

func (x *GameStatus) GetGameStatus() Status {
	if x != nil {
		return x.GameStatus
	}
	return Status_NOT_ATTEMPTED
}

type WordStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstCharacter  CharacterStatus `protobuf:"varint,1,opt,name=firstCharacter,proto3,enum=main.CharacterStatus" json:"firstCharacter,omitempty"`
	SecondCharacter CharacterStatus `protobuf:"varint,2,opt,name=secondCharacter,proto3,enum=main.CharacterStatus" json:"secondCharacter,omitempty"`
	ThirdCharacter  CharacterStatus `protobuf:"varint,3,opt,name=thirdCharacter,proto3,enum=main.CharacterStatus" json:"thirdCharacter,omitempty"`
	FourthCharacter CharacterStatus `protobuf:"varint,4,opt,name=fourthCharacter,proto3,enum=main.CharacterStatus" json:"fourthCharacter,omitempty"`
	FifthCharacter  CharacterStatus `protobuf:"varint,5,opt,name=fifthCharacter,proto3,enum=main.CharacterStatus" json:"fifthCharacter,omitempty"`
}

func (x *WordStatus) Reset() {
	*x = WordStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordStatus) ProtoMessage() {}

func (x *WordStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordStatus.ProtoReflect.Descriptor instead.
func (*WordStatus) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{6}
}

func (x *WordStatus) GetFirstCharacter() CharacterStatus {
	if x != nil {
		return x.FirstCharacter
	}
	return CharacterStatus_NOT_PRESENT
}

func (x *WordStatus) GetSecondCharacter() CharacterStatus {
	if x != nil {
		return x.SecondCharacter
	}
	return CharacterStatus_NOT_PRESENT
}

func (x *WordStatus) GetThirdCharacter() CharacterStatus {
	if x != nil {
		return x.ThirdCharacter
	}
	return CharacterStatus_NOT_PRESENT
}

func (x *WordStatus) GetFourthCharacter() CharacterStatus {
	if x != nil {
		return x.FourthCharacter
	}
	return CharacterStatus_NOT_PRESENT
}

func (x *WordStatus) GetFifthCharacter() CharacterStatus {
	if x != nil {
		return x.FifthCharacter
	}
	return CharacterStatus_NOT_PRESENT
}

type RanksHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllRanks []*DayRanks `protobuf:"bytes,1,rep,name=allRanks,proto3" json:"allRanks,omitempty"`
}

func (x *RanksHistory) Reset() {
	*x = RanksHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RanksHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RanksHistory) ProtoMessage() {}

func (x *RanksHistory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RanksHistory.ProtoReflect.Descriptor instead.
func (*RanksHistory) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{7}
}

func (x *RanksHistory) GetAllRanks() []*DayRanks {
	if x != nil {
		return x.AllRanks
	}
	return nil
}

type DayRanks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranks []*Rank `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"`
}

func (x *DayRanks) Reset() {
	*x = DayRanks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayRanks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayRanks) ProtoMessage() {}

func (x *DayRanks) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayRanks.ProtoReflect.Descriptor instead.
func (*DayRanks) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{8}
}

func (x *DayRanks) GetRanks() []*Rank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

type Rank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string               `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Time     *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Rank     int64                `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *Rank) Reset() {
	*x = Rank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_wordle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_protos_wordle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_protos_wordle_proto_rawDescGZIP(), []int{9}
}

func (x *Rank) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Rank) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Rank) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_protos_wordle_proto protoreflect.FileDescriptor

var file_protos_wordle_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x09,
	0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x71, 0x0a, 0x11, 0x57, 0x6f, 0x72,
	0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x09,
	0x77, 0x6f, 0x72, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x26, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xcb, 0x02, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0e, 0x74, 0x68, 0x69, 0x72, 0x64, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x74, 0x68, 0x69, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0f, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0f, 0x66, 0x6f, 0x75, 0x72, 0x74, 0x68, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0e, 0x66, 0x69, 0x66, 0x74, 0x68, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x66, 0x69, 0x66, 0x74, 0x68, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x52, 0x61, 0x6e, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44,
	0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x52, 0x61, 0x6e, 0x6b,
	0x73, 0x22, 0x2c, 0x0a, 0x08, 0x44, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x20, 0x0a,
	0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x22,
	0x66, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x2a, 0x4a, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f,
	0x54, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50,
	0x52, 0x45, 0x53, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x55, 0x54, 0x5f, 0x4d, 0x49, 0x53, 0x50, 0x4c,
	0x41, 0x43, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x52, 0x52, 0x45, 0x43,
	0x54, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a,
	0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x54, 0x54, 0x45, 0x4d, 0x50, 0x54, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x57, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0x03,
	0x32, 0xc7, 0x02, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x1a, 0x17, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a,
	0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x4d, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x52, 0x61, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64,
	0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x61, 0x6e, 0x6b,
	0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_wordle_proto_rawDescOnce sync.Once
	file_protos_wordle_proto_rawDescData = file_protos_wordle_proto_rawDesc
)

func file_protos_wordle_proto_rawDescGZIP() []byte {
	file_protos_wordle_proto_rawDescOnce.Do(func() {
		file_protos_wordle_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_wordle_proto_rawDescData)
	})
	return file_protos_wordle_proto_rawDescData
}

var file_protos_wordle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_wordle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_wordle_proto_goTypes = []interface{}{
	(CharacterStatus)(0),        // 0: main.CharacterStatus
	(Status)(0),                 // 1: main.Status
	(*EmptyMessage)(nil),        // 2: main.EmptyMessage
	(*WordGuess)(nil),           // 3: main.WordGuess
	(*WordGuessResponse)(nil),   // 4: main.WordGuessResponse
	(*UserName)(nil),            // 5: main.UserName
	(*StartResponse)(nil),       // 6: main.StartResponse
	(*GameStatus)(nil),          // 7: main.GameStatus
	(*WordStatus)(nil),          // 8: main.WordStatus
	(*RanksHistory)(nil),        // 9: main.RanksHistory
	(*DayRanks)(nil),            // 10: main.DayRanks
	(*Rank)(nil),                // 11: main.Rank
	(*timestamp.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_protos_wordle_proto_depIdxs = []int32{
	1,  // 0: main.WordGuessResponse.gameStatus:type_name -> main.Status
	8,  // 1: main.WordGuessResponse.wordMatch:type_name -> main.WordStatus
	1,  // 2: main.GameStatus.gameStatus:type_name -> main.Status
	0,  // 3: main.WordStatus.firstCharacter:type_name -> main.CharacterStatus
	0,  // 4: main.WordStatus.secondCharacter:type_name -> main.CharacterStatus
	0,  // 5: main.WordStatus.thirdCharacter:type_name -> main.CharacterStatus
	0,  // 6: main.WordStatus.fourthCharacter:type_name -> main.CharacterStatus
	0,  // 7: main.WordStatus.fifthCharacter:type_name -> main.CharacterStatus
	10, // 8: main.RanksHistory.allRanks:type_name -> main.DayRanks
	11, // 9: main.DayRanks.ranks:type_name -> main.Rank
	12, // 10: main.Rank.time:type_name -> google.protobuf.Timestamp
	3,  // 11: main.GameService.Submit:input_type -> main.WordGuess
	5,  // 12: main.GameService.Start:input_type -> main.UserName
	5,  // 13: main.GameService.GetGameStatus:input_type -> main.UserName
	5,  // 14: main.GameService.GetMyRank:input_type -> main.UserName
	2,  // 15: main.GameService.GetTodayRanks:input_type -> main.EmptyMessage
	2,  // 16: main.GameService.GetRanksHistory:input_type -> main.EmptyMessage
	4,  // 17: main.GameService.Submit:output_type -> main.WordGuessResponse
	6,  // 18: main.GameService.Start:output_type -> main.StartResponse
	7,  // 19: main.GameService.GetGameStatus:output_type -> main.GameStatus
	11, // 20: main.GameService.GetMyRank:output_type -> main.Rank
	10, // 21: main.GameService.GetTodayRanks:output_type -> main.DayRanks
	9,  // 22: main.GameService.GetRanksHistory:output_type -> main.RanksHistory
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protos_wordle_proto_init() }
func file_protos_wordle_proto_init() {
	if File_protos_wordle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_wordle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordGuess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordGuessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RanksHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayRanks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_wordle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_wordle_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_wordle_proto_goTypes,
		DependencyIndexes: file_protos_wordle_proto_depIdxs,
		EnumInfos:         file_protos_wordle_proto_enumTypes,
		MessageInfos:      file_protos_wordle_proto_msgTypes,
	}.Build()
	File_protos_wordle_proto = out.File
	file_protos_wordle_proto_rawDesc = nil
	file_protos_wordle_proto_goTypes = nil
	file_protos_wordle_proto_depIdxs = nil
}
